# Generated by Django 3.2.5 on 2021-12-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_alter_issue_linked_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='state',
            field=models.IntegerField(null=True),
        ),
    ]
