# Generated by Django 3.2.5 on 2021-12-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_issue_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='platform',
            field=models.IntegerField(choices=[(0, 'Android'), (1, 'Ios'), (2, 'Chrome'), (3, 'Safari'), (4, 'Firefox')], default=1),
        ),
        migrations.AddField(
            model_name='issue',
            name='screenshot',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='issue',
            name='version',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='state',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
